### ISSUE TITLE
ImportError: cannot import name 'load_rednet' from 'RedNet.RedNet_model'

### ISSUE THREAD

**Issue by Leo24-m** [shalexyuan/GAMap#1]
**Issue Description:**
When I try to run the following command in my GAMap environment:

`python ga.py --split val_mini --eval 0 --auto_gpu_config 0 -n 1 --num_eval_episodes 2000 --use_gtsem 0 --num_local_steps 10 --exp_name gamap --agent multi_attr_exp`

**I get the following ImportError:**
`Traceback (most recent call last):
  File "/home/ailabsm/GAMap/ga.py", line 21, in <module>
    from model_multi import Semantic_Mapping, FeedforwardNet
  File "/home/ailabsm/GAMap/model_multi.py", line 11, in <module>
    import envs.utils.depth_utils_multi as du
  File "/home/ailabsm/GAMap/envs/__init__.py", line 3, in <module>
    from .habitat import construct_envs, construct_envs21
  File "/home/ailabsm/GAMap/envs/habitat/__init__.py", line 13, in <module>
    from agents.sem_exp import Sem_Exp_Env_Agent
  File "/home/ailabsm/GAMap/agents/sem_exp.py", line 20, in <module>
    from RedNet.RedNet_model import load_rednet
ImportError: cannot import name 'load_rednet' from 'RedNet.RedNet_model' (/home/ailabsm/GAMap/RedNet/RedNet_model.py)`

**Steps to Reproduce:**

1. Navigate to the GAMap directory.

2. Run the ga.py script with the specified arguments as shown above.

**System Information:**

- Operating System: Ubuntu 20.04

- Python Version: 3.9.19 (in the habitat environment)

- GAMap directory: /home/ailabsm/GAMap

**Potential Cause and Observations:**
It seems like there is an issue with importing the load_rednet function from the RedNet_model.py file. I have verified that the RedNet_model.py file exists in the specified path, but the function load_rednet may not be properly defined or there might be a typo.

**Questions/Request for Help:**

- Could there be an issue with the version of the RedNet code I am using?

- Is there a specific requirement or dependency needed for the RedNet_model.py to work correctly?

- Any guidance on how to resolve this import error would be appreciated.

**Comment by Leo24-m** [comment]
### ImportError in RedNet_model.py: Cannot Import 'utils' from 'utils'

**I encountered an ImportError when trying to run ga.py:**

```
(gamap) ailabsm@ailabsm-MS-7B28:~/GAMap$ python ga.py --split val_mini --eval 0 --auto_gpu_config 0 -n 1 --num_eval_episodes 2000 --use_gtsem 0 --num_local_steps 10 --exp_name gamap --agent multi_attr_exp
Traceback (most recent call last):
  File "/home/ailabsm/GAMap/ga.py", line 21, in <module>
    from model_multi import Semantic_Mapping, FeedforwardNet
  File "/home/ailabsm/GAMap/model_multi.py", line 11, in <module>
    import envs.utils.depth_utils_multi as du
  File "/home/ailabsm/GAMap/envs/__init__.py", line 3, in <module>
    from .habitat import construct_envs, construct_envs21
  File "/home/ailabsm/GAMap/envs/habitat/__init__.py", line 13, in <module>
    from agents.sem_exp import Sem_Exp_Env_Agent
  File "/home/ailabsm/GAMap/agents/sem_exp.py", line 20, in <module>
    from RedNet.RedNet_model import load_rednet
  File "/home/ailabsm/GAMap/RedNet/RedNet_model.py", line 5, in <module>
    from utils import utils
ImportError: cannot import name 'utils' from 'utils' (unknown location)
```

**I managed to solve this problem by modifying the import statement in RedNet/RedNet_model.py:**

# Original code:
`from utils import utils `

# Modified code:
`from RedNet.utils import utils`


**I'm using RedNet-related repositories cloned from [this GitHub repository](https://github.com/JindongJiang/RedNet).**

**I hope this helps anyone else encountering the same issue!**

**Comment by shalexyuan** [comment]
Hi @Leo24-m I've uploaded the RedNet. Please use the provided one.
